### PR TITLE
Make IsEmpty() and Is().Empty() independent of size() method

### LINKED ISSUE #14: IsEmpty() should check for `.empty()`, not `.size() == 0`

### PR DESCRIPTION
**Pull request by sbeyer**
Fixes #14.

### CODE REVIEW

**Comment by nabijaczleweli** [comment]
aw hell yeah boi

**Comment by sbeyer** [comment]
@nabijaczleweli I'd be very happy if you could test the current snowhouse master branch in your projects to see if I f*cked up something. There are a few compatibility-breaking changes, but probably the only one that is noticed by ordinary users is that you *have* to use a semi-colon after `AssertThat` etc. now.

**Comment by nabijaczleweli** [comment]
The code using snowhouse (via bandit), now 1.5-year-old, works after updating both to newest (first bandit, then forcing `master` snowhouse over the 2-month-old one) with very minor adjustments. Good shit. :+1:

**Comment by sbeyer** [comment]
Thank you very much!

**Pull request merged**
